name: Test daily builds

on:
  schedule:
  - cron: "0 5 * * *"

jobs:
  test-daily-master:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install nextcloud
        run: sudo snap install --edge nextcloud

      - name: Setup ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration

  test-daily-v30:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install nextcloud
        run: sudo snap install nextcloud --channel=30/edge

      - name: Setup ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration

  test-daily-v31:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install nextcloud
        run: sudo snap install nextcloud --channel=31/edge

      - name: Setup ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration

  test-daily-v32:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install nextcloud
        run: sudo snap install nextcloud --channel=32/edge

      - name: Setup ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration
